spawn:
  all:
    x: 0.0
    y: 4.0
    z: 0.0
  red:
    x: 100.0
    y: 6.0
    z: 100.0
  blue:
    x: 100.0
    y: 3.0
    z: -100.0
  yellow:
    x: -100.0
    y: 4.0
    z: -100.0
  green:
    x: -100.0
    y: 4.0
    z: 100.0
block:
  buff:
    x: 0.0
    y: 40.0
    z: 0.0
ctf:
  red:
    curr: {}
  blue:
    curr: {}
  yellow:
    curr: {}
  green:
    curr: {}
kills:
  red: 0
  blue: 0
  yellow: 0
  green: 0
base:
  protection:
    radius: 50
count:
  red: 0
  blue: 0
  yellow: 0
  green: 0
