teams:
  red:
    block: wool:13
    color: red
    spawn:
      region:
      x:
      y:
      z:
    flag:
      region:
      x:
      y:
      z:
    server: 
  blue:
    block: wool:11
    color: blue
    spawn:
      region:
      x:
      y:
      z:
    flag:
      region:
      x:
      y:
      z:
    server: 
staff:
  group: moderators
  head_block: 'whool:0'
  chat_color: white
