name: CutePVP
main: com.c45y.CutePVP.CutePVP
version: 1.1
softdepend: [WorldGuard, ServerMessengerPlugin]

permissions:
    CutePVP.player:
        description: a user
        default: true
    CutePVP.mod:
        description: mod
        default: op
    CutePVP.modmode:
        description: modmode
        default: not op
    CutePVP.admin:
        description: admin
        default: op
        children:
            CutePVP.mod: true

commands:
  g:
    description: Global chat
    permission: CutePVP.player
    usage: |
           /g [message]
  list:
    description: lists teams
    permissions: CutePVP.player
    usage: |
           /list
  score:
    description: teams score
    permissions: CutePVP.player
    usage: |
           /score
  drop:
    description: drop flag
    permissions: CutePVP.player
    usage: |
           /drop
  flag:
    description: displays flag location
    permissions: CutePVP.player
    usage: |
           /flag
  ctf:
    description: CTF stuff
    permission: CutePVP.mod
    usage: |
           /ctf [stuff]
  cutepvp:
    description: CutePVP stuff
    permission: CutePVP.admin
    usage: |
           /cutepvp [stuff]
