name: CutePVP
main: com.c45y.CutePVP.CutePVP
version: 0.9
permissions:
    CutePVP.mod:
        description: asdf
        default: op
commands:
  asdf:
    description: set config things
    permission: CutePVP.mod
    usage: |
           /asdf: set config things